In [3]:
print("Hello")

Hello


In [4]:
import numpy as np

# creating an 1d array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
#  reshaping the 1d array
arr2 = arr1.reshape(1,5)
print(arr2)
# 2d and 3d arrays
arr3 = np.array([arr1, [6,7,8,9,10]])
print(arr3.shape, arr3)

[[1 2 3 4 5]]
(2, 5) [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
# arrange function
# np.arange(0,10,4)
# np.arange(0,10,2).reshape(5,1)
# identity matrix
# np.eye(2)
# fill ones
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array: ", arr)
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size of arr: ", arr.size)
print("Data type: ", arr.dtype)
print("Item size(in bytes): ", arr.itemsize)

Array:  [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size of arr:  6
Data type:  int64
Item size(in bytes):  8


In [13]:
# Verctorized Operations
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])
# arr2 = np.array([10,20,30,40,50]) => this will give an error

# Element wise addition
print("Addition: ", arr1+arr2)
print("Substraction:", arr1-arr2)
print("Multiplication:", arr1*arr2)
print("Division:", arr1/arr2)

# Dot Product
print("Dot Product:")
print(np.dot(arr1,arr2))

Addition:  [11 22 33 44]
Substraction: [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Division: [0.1 0.1 0.1 0.1]
Dot Product:
300


In [9]:
arr = np.array([1,2,3,4,5])
print("Sq. root: ", np.sqrt(arr))
print("Exponential: ", np.exp(arr))
print("Sine: ", np.sin(arr))
print("Log: ", np.log(arr))

Sq. root:  [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Log:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [10]:
#  array slicing and indexing
# arr = np.array([[[1],[2],[3]],[[4],[5],[6]]])
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print("Array: ",arr)
print("\n", arr[0:2,1:])
print("\n", arr[0:,1:])
print(arr[1:])
print(arr.T)



 [[2 3]
 [5 6]]

 [[2 3]
 [5 6]
 [8 9]]
[[4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
#  statistical concept: Normalization 
#  mean = 0 and std. devi = 1
data = np.array([10,58,345,21,45])
mean = np.mean(data)
std_dev = np.std(data)
noramlized_data = (data - mean)/std_dev
print("Mean: ",mean)
print("Std. Devi.: ", std_dev)
print("Var: ", np.var(data))
print("Normalized Data: ", noramlized_data)

Mean:  95.8
Std. Devi.:  125.75118289702088
Var:  15813.359999999997
Normalized Data:  [-0.68229974 -0.30059359  1.9816911  -0.59482542 -0.40397234]


In [12]:
# Logical operations
data = np.array([1,2,3,4,5,6,7,8,9])
print(data>6)
print(data[data>6])

[False False False False False False  True  True  True]
[7 8 9]
