## Introduction to Scikit-Learn
Steps:
0. An end-to-end scikit-learn workflow
1. Getting data ready
2. Choose the right estimator/algorithm for our problems
3. Fit the model/algorithm
4. Evaluating a model
5. Improve a model
6. save and load a trained model
7. putting it all together

End-to-End Workflow

In [11]:
import pandas as pd
import numpy as np
heart_disease=pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [12]:
#1.Getting Data Ready
#Create X (feature matrix)
X=heart_disease.drop("target",axis=1)
#Create y (labels, the target column)
y=heart_disease["target"]

In [52]:
#2.Choose the right model and hyperparameter
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
#Keeping the default hyperparameter,optional
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [53]:
#3.Fit the Model to the training data
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((227, 13), (76, 13), (227,), (76,))

In [54]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [55]:
#make a prediction
y_preds=model.predict(X_test)

In [56]:
y_preds

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [57]:
heart_disease.loc[206]

age          59.0
sex           1.0
cp            0.0
trestbps    110.0
chol        239.0
fbs           0.0
restecg       0.0
thalach     142.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
target        0.0
Name: 206, dtype: float64

In [59]:
X_test.loc[233]

age          64.0
sex           1.0
cp            0.0
trestbps    120.0
chol        246.0
fbs           0.0
restecg       0.0
thalach      96.0
exang         1.0
oldpeak       2.2
slope         0.0
ca            1.0
thal          2.0
Name: 233, dtype: float64

In [60]:
heart_disease.loc[233]

age          64.0
sex           1.0
cp            0.0
trestbps    120.0
chol        246.0
fbs           0.0
restecg       0.0
thalach      96.0
exang         1.0
oldpeak       2.2
slope         0.0
ca            1.0
thal          2.0
target        0.0
Name: 233, dtype: float64

In [61]:
model.predict(np.array(X_test.loc[233]).reshape(1,-1))

C:\Users\Vinit Solanki\myenv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [62]:
model.score(X_train,y_train)

1.0

In [63]:
model.score(X_test,y_test)

0.881578947368421

In [65]:
np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimators...")
    model=RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print(f"Model accuracy on test set:{model.score(X_test,y_test)}")
    print("")

Trying model with 10 estimators...
Model accuracy on test set:0.881578947368421

Trying model with 20 estimators...
Model accuracy on test set:0.8552631578947368

Trying model with 30 estimators...
Model accuracy on test set:0.8552631578947368

Trying model with 40 estimators...
Model accuracy on test set:0.868421052631579

Trying model with 50 estimators...
Model accuracy on test set:0.868421052631579

Trying model with 60 estimators...
Model accuracy on test set:0.8947368421052632

Trying model with 70 estimators...
Model accuracy on test set:0.9078947368421053

Trying model with 80 estimators...
Model accuracy on test set:0.8947368421052632

Trying model with 90 estimators...
Model accuracy on test set:0.868421052631579



In [66]:
from sklearn.model_selection import cross_val_score
np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimators...")
    model=RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print(f"MOdel accuracy on test set: {model.score(X_test,y_test)}")
    print(f"Cross-validation score:{np.mean(cross_val_score(model,X,y,cv=5))*100}%")
    print("")

Trying model with 10 estimators...
MOdel accuracy on test set: 0.881578947368421
Cross-validation score:78.53551912568305%

Trying model with 20 estimators...
MOdel accuracy on test set: 0.8947368421052632
Cross-validation score:79.84699453551912%

Trying model with 30 estimators...
MOdel accuracy on test set: 0.8947368421052632
Cross-validation score:80.50819672131148%

Trying model with 40 estimators...
MOdel accuracy on test set: 0.8552631578947368
Cross-validation score:82.15300546448088%

Trying model with 50 estimators...
MOdel accuracy on test set: 0.868421052631579
Cross-validation score:81.1639344262295%

Trying model with 60 estimators...
MOdel accuracy on test set: 0.881578947368421
Cross-validation score:83.47540983606557%

Trying model with 70 estimators...
MOdel accuracy on test set: 0.8947368421052632
Cross-validation score:81.83060109289617%

Trying model with 80 estimators...
MOdel accuracy on test set: 0.8947368421052632
Cross-validation score:82.81420765027322%

Tryi

In [67]:
import pickle
pickle.dump(model,open("random_forest_model_1.pkl","wb"))

In [69]:
loaded_model=pickle.load(open("random_forest_model_1.pkl","rb"))
loaded_model.predict(np.array(X_test.loc[233]).reshape(1,-1))

C:\Users\Vinit Solanki\myenv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [70]:
import sklearn
sklearn.show_versions()


System:
    python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
executable: C:\Users\Vinit Solanki\myenv\Scripts\python.exe
   machine: Windows-11-10.0.22631-SP0

Python dependencies:
      sklearn: 1.4.2
          pip: 24.0
   setuptools: None
        numpy: 1.26.4
        scipy: 1.13.0
       Cython: None
       pandas: 2.2.2
   matplotlib: 3.8.4
       joblib: 1.4.2
threadpoolctl: 3.5.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
    num_threads: 8
         prefix: libopenblas
       filepath: C:\Users\Vinit Solanki\myenv\Lib\site-packages\numpy.libs\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll
        version: 0.3.23.dev
threading_layer: pthreads
   architecture: Zen

       user_api: openmp
   internal_api: openmp
    num_threads: 8
         prefix: vcomp
       filepath: C:\Users\Vinit Solanki\myenv\Lib\site-packages\sklearn\.libs\vcomp140.dll
        ve

In [72]:
  what_were_covering=[
      "0.end-to-end scikit-learn workflow",
      "1.getting data ready",
      "2 hoose the right estimator/model for our problems",
      "3.fit the model/algorithm and use it to make predictions",
      "4.evaluate the model",
      "5.improve a model by changing the hyperparameter",
      "6.save and load a trained model",
      "7.putting, saving all together",
  ]

## 1.Getting data ready

There are three main things to be done:
        1. Split the data into features and labels (X & y)
        2. Fitting or disgrading missing values
        3. Converting non-numerical values to numerical values  (also called feature encoding)