In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from sklearn.datasets import make_classification

In [4]:
X, y = make_classification(n_samples=100, n_classes=2, n_features=10, random_state=42)

In [5]:
X = pd.DataFrame(X)
X

0         1         2         3         4         5         6  \
0  -1.140526  1.359706  0.861991  0.846092  0.606010 -1.556629  1.754794   
1  -0.078734 -1.329332  0.627375 -1.193006 -0.773010  0.097676  0.497998   
2   0.807427  0.730198 -1.285680  0.889484 -1.804882 -0.763259  0.048085   
3   0.588465 -0.375121 -0.575002 -0.149518 -0.563725  0.412931  0.243687   
4   1.636312 -1.640607 -1.360456 -0.941163 -1.430141  1.632411  0.130741   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.531047  0.948005 -1.032233  0.996309 -1.008086 -2.038125 -0.351513   
96 -0.963142  0.556003  0.964233  0.193754 -0.703176  1.149273  1.770801   
97  0.950573 -2.255540 -0.270624 -1.692005  0.504047 -0.985726 -0.792873   
98 -1.016951  0.554484  1.031102  0.175930  0.615936 -1.081063 -0.309546   
99  1.897924 -1.614533 -1.693028 -0.838070  0.791663  1.158111  0.628346   

           7         8         9  
0   1.696456 -1.280429 -2.081929  
1   0.959271  0.024510  1.451144  
2  -0.904317 -1.627542  0.259723  
3  -0.506943 -0.822220  0.244967  
4  -1.435862 -0.440044  1.441273  
..       ...       ...       ...  
95  1.676437 -1.870792  0.018418  
96  1.812449 -0.034988 -0.626967  
97 -1.035242 -0.530258 -0.107030  
98 -1.251114  0.593101  0.326133  
99 -0.897254  0.624120 -0.012247  

[100 rows x 10 columns]

In [6]:
y

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [10]:
logistic.fit(X_train, y_train)

LogisticRegression()

In [11]:
y_pred = logistic.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0])

In [12]:
logistic.predict_proba(X_test)

array([[9.04675251e-01, 9.53247494e-02],
       [7.97965075e-02, 9.20203492e-01],
       [1.33736145e-02, 9.86626386e-01],
       [7.86373395e-02, 9.21362661e-01],
       [2.07691091e-02, 9.79230891e-01],
       [9.72546031e-01, 2.74539693e-02],
       [9.78171609e-01, 2.18283908e-02],
       [2.54443533e-01, 7.45556467e-01],
       [2.14117582e-01, 7.85882418e-01],
       [1.65396820e-01, 8.34603180e-01],
       [9.88737978e-01, 1.12620223e-02],
       [2.80587665e-03, 9.97194123e-01],
       [7.85824805e-04, 9.99214175e-01],
       [9.99130522e-01, 8.69477913e-04],
       [5.13601693e-03, 9.94863983e-01],
       [9.67299512e-01, 3.27004880e-02],
       [3.91255210e-02, 9.60874479e-01],
       [9.82741573e-01, 1.72584274e-02],
       [9.69083770e-01, 3.09162297e-02],
       [9.97698675e-01, 2.30132477e-03]])

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

score = accuracy_score(y_test, y_pred)
score

1.0

In [14]:
cfm = confusion_matrix(y_test, y_pred)
cfm

array([[ 9,  0],
       [ 0, 11]])

In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



Hyperparameter Tuning

In [18]:
model = LogisticRegression()
penalty = ['l1','l2','elasticnet']
c_values = [100, 10, 1, 0,1, 0.01, 0.2, 0.3, 3, 5]
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [20]:
params = dict(penalty= penalty, C= c_values, solver= solver )

In [21]:
# GridSearchCV
from sklearn.model_selection import GridSearchCV, StratifiedKFold

cv = StratifiedKFold()
grid = GridSearchCV(estimator= model, param_grid= params, scoring= 'accuracy', cv= cv, n_jobs=-1)

In [22]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0, 1, 0.01, 0.2, 0.3, 3, 5],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [23]:
grid.fit(X_train, y_train)

c:\Users\Vinit Solanki\OneDrive\Documents\ML&DS\myenv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
435 fits failed out of a total of 750.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Vinit Solanki\OneDrive\Documents\ML&DS\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Vinit Solanki\OneDrive\Documents\ML&DS\myenv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vinit Solanki

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0, 1, 0.01, 0.2, 0.3, 3, 5],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [24]:
grid.best_params_

{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}

In [25]:
grid.best_score_

np.float64(0.975)

In [26]:
y_pred = grid.predict(X_test)

In [28]:
score = accuracy_score(y_pred, y_test)
print(score)

1.0


In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [32]:
print(confusion_matrix(y_test, y_pred))

[[ 9  0]
 [ 0 11]]


Randomized Search CV

In [34]:
from sklearn.model_selection import RandomizedSearchCV

In [35]:
model = LogisticRegression()
rcv = RandomizedSearchCV(estimator=model, param_distributions=params, cv= 5, scoring= 'accuracy')

In [36]:
rcv.fit(X_train, y_train)

c:\Users\Vinit Solanki\OneDrive\Documents\ML&DS\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Vinit Solanki\OneDrive\Documents\ML&DS\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Vinit Solanki\OneDrive\Documents\ML&DS\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Vinit Solanki\OneDrive\Documents\ML&DS\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Vinit Solanki\OneDrive\Documents\ML&DS\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0, 1, 0.01, 0.2, 0.3,
                                              3, 5],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [37]:
rcv.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 1}

In [38]:
rcv.best_score_

np.float64(0.95)

In [39]:
rcv.predict(X_test)

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0])

In [40]:
score = accuracy_score(y_pred, y_test)
print(score)

1.0


In [41]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [42]:
confusion_matrix(y_test, y_pred)

array([[ 9,  0],
       [ 0, 11]])